name: Validate

on: [push, pull_request]

jobs:
  validate:
    if: "(!contains(github.event.commits[0].message, '[skip ci]')) && (!contains(github.event.commits[0].message, '[ci skip]'))"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Python 3 🔧
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies 🔧
        run: |
          pip install -r requirements.txt

      - name: Check 🔍
        run: |
          cd tools
          python workflow.py -c --noconfirm

  deploy:
    if: github.event_name == 'push'
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Invoke remote
        run: |
          curl -XPOST "https://suisei-podcast.outv.im/rpc?key=${{ secrets.BIN_API_KEY }}&reason=gh_${{ github.sha }}&delay=1&action=fetch_clip"
